services:
  mysql:
    image: mysql:8-oracle
    environment:
      MYSQL_DATABASE: db_sql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./docker-data/mysql/:/var/lib/mysql